# Generated by Django 2.1.5 on 2019-02-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typefood_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='typefood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoiHiso.TypeFood'),
        ),
    ]
